> sim RTL ysyx Yao Yibo Linux yyb-virtual-machine 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux  08:52:32 up  3:49,  1 user,  load average: 0.29, 0.15, 0.31

diff --git a/npc/Makefile b/npc/Makefile
--- a/npc/Makefile
+++ b/npc/Makefile
@@ -1,8 +1,25 @@
+VERILATOR = verilator
+VERILATOR_FLAGS = -Wall $(SRC_DIR)/top.v $(SRC_DIR)/top_main.cpp --cc --trace --exe --build
+SRC_DIR = ../../verilator/examples/switch
+OBJ_DIR = $(SRC_DIR)/obj_dir
+EXECUTABLE = $(OBJ_DIR)/Vtop
+WAVE_VCD = $(SRC_DIR)/wave.vcd
+
+.PHONY:all clean sim
+
 all:
-	@echo "Write this Makefile by your self."
+	@echo "No default target.Use 'make sim' to run the simulation."
 
 sim:
 	$(call git_commit, "sim RTL") # DO NOT REMOVE THIS LINE!!!
-	@echo "Write this Makefile by your self."
+	$(VERILATOR) $(VERILATOR_FLAGS)
+	$(EXECUTABLE) &> /dev/null & PID=$$!; sleep 10;kill -9 $$PID
+	@if ! command -v gtkwave &> /dev/null; then \
+		echo "gtkwave not found.Installing gtkwave and dependencie..."; \
+                sudo apt-get update && sudo apt-get install -y gtkwave libcanberra-gtk-module; \
+        fi
+	gtkwave $(WAVE_VCD); \
+clean:
+	rm -rf $(OBJ_DIR) $(WAVE_VCD) 
 
 include ../Makefile
